const express = require('express');
const router = express.Router();
const userController = require('../controllers/user-controller');
router.post('/register', userController.Register);
router.post('/login', userController.Login);
router.get('/getpendingsponsor', userController.getPendingSponsor);
router.get('/getpendingcollege', userController.getPendingCollege);
router.get('/getcollegelist', userController.getCollegeList);
router.get('/getsponsorlist', userController.getSponsorList);
router.post('/updatestatus', userController.updateStatus);
router.post('/changepassword', userController.changePassword);
module.exports = router;
